name: ASP.NET Core Build

on: [push]

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.0.100
  build:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
     - name: Dotnet restore
        run: make deps
      - name: Dotnet build
        run: make build

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Dotnet test
        run: make test

  integrationtest:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Dotnet integrationtest
        run: make integrationtest
