name: ASP.NET Core Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.0
      - name: Dotnet restore
        run: make deps

      - name: Dotnet build
        run: make build

      - name: Dotnet test
        run: make test

      - name: Dotnet integrationtest
        run: make integrationtest
